---
name: CI Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docker-publish:
    defaults:
      run:
        shell: bash

    runs-on: forgejo

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - uses: https://git.luzifer.io/luzifer-arch/updpkgsums-action@408d9469939be2e5e714c1717838ab6237bf58cc

      - uses: stefanzweifel/git-auto-commit-action@v5.2.0
        with:
          file_pattern: PKGBUILD
